// ===== ЛОКАЛИЗАЦИЯ v110 =====
var LANG_KEY="clicker-lang";
var LANG={
ru:{
// ===== ОБЩЕЕ =====
"common.close":"✕ Закрыть","common.close_x":"✖ Закрыть","common.cancel":"✖ Отмена",
"common.ok":"✅ ОК","common.yes":"Да","common.no":"Нет","common.error":"Ошибка",
"common.loading":"Загрузка...",
"common.seconds_short":" с","common.minutes_short":" мин","common.hours_short":" ч ",
"common.coins_word":"монет",

// ===== ТАБЫ =====
"tab.items":"🛒 Магазин","tab.boosters":"📦 Бустеры","tab.achievements":"🏆 Достижения",
"tab.quests":"📜 Задания","tab.leaders":"🥇 Лидеры","tab.friends":"👥 Друзья",
"tab.skins":"🎨 Скины","tab.stats":"📊 Статистика","tab.settings":"⚙️ Настройки",
"tab.help":"❓ Помощь","tab.reward":"🏅 Награда","tab.note":"📜 Записка",

// ===== ГЛАВНАЯ =====
"main.coins":"монет","main.per_second":"В секунду",
"main.hungry":"😭 Голодный смайлик: −5M монет/сек",
"main.gulau_mult":"×5 тапов, осталось","main.crystals":"💎 Кристаллов",
"main.blood_moon":"🌕 Кровавая луна! До конца","main.shards":"🌑 Кровавых осколков",
"main.bonus":"⚔️ Бонус","main.tap":"ТАП",
"main.generator":"⚡ Генератор: Ур. 1","main.generator_word":"Генератор",
"main.chest":"🎁 Сундук","main.wheel":"🎡 Фортуна","main.daily":"📅 Ежедневка",
"main.minigame":"⏱️ Мини-игра","main.fnf":"🥊 Битва с Крохлюпиком",
"main.fortune":"🥠 Что сегодня?","main.fortune_wait":"🥠 До завтра",
"main.shop_title":"Магазин улучшений","main.shop_upgrades":"Улучшения",
"main.shop_global":"Гл. улучшения",
"season.rating":"Сезонный рейтинг","season.left":"До конца",

// ===== ПИТОМЦЫ =====
"pets.title":"🐾 ПИТОМЦЫ","pets.buy_egg":"🥚 Купить яйцо — 65 💎",
"pets.tap_3":"👆 Тапни 3 раза!","pets.tap_collect":"👆 Тапни — забери питомца!",
"pets.storage":"📦 ХРАНИЛИЩЕ","pets.empty":"Пусто",
"pets.active_title":"⭐ АКТИВНЫЙ ПИТОМЕЦ","pets.no_active":"Нет активного питомца",
"pets.hunger":"🍽️ Голод","pets.deactivate":"↩️ Убрать в хранилище",
"pets.food_shop_title":"🛒 МАГАЗИН ЕДЫ",
"pets.food_hunger_5":"+5 голода","pets.food_hunger_10":"+10 голода",
"pets.food_hunger_20":"+20 голода",
"pets.buy":"Купить","pets.feed":"Покормить","pets.activate":"Активировать",
"pets.sell":"Продать",
"pets.rarity_common":"🟢 Обычный","pets.rarity_rare":"🔵 Редкий",
"pets.rarity_epic":"🟣 Эпический","pets.age":"Возраст",
"pets.feed_success":"✅ Питомец накормлен!","pets.feed_no_food":"❌ Нет такой еды!",
"pets.pet_died":"💀 Твой {pet} погиб от голода...",
"pets.no_money_food":"❌ Недостаточно ⭐ для покупки еды!",
"pets.storage_full":"Хранилище заполнено (5/5)!",
"pets.name_hamster":"Хомяк","pets.name_kitten":"Котёнок","pets.name_fox":"Лисёнок",
"pets.name_penguin":"Пингвин","pets.name_wolf":"Волчонок","pets.name_dragon":"Дракончик",
"pets.name_phoenix":"Феникс",
"pet.bonus_income":"% доход","pet.bonus_gem":"% гем","pet.bonus_shard":"% осколок",
"pet.sell_price":"Цена продажи","pet.egg_chance":"Шанс из яйца",

// ===== СМЕРТИ ПИТОМЦЕВ =====
"petdeath.hamster":"Твой Хомяк погиб от голода... Он был верным другом.",
"petdeath.kitten":"Твой Котёнок погиб от голода... Он мурлыкал до последнего.",
"petdeath.fox":"Твой Лисёнок погиб от голода... Хитрый, но голодный.",
"petdeath.penguin":"Твой Пингвин погиб от голода... Ему не хватило рыбы.",
"petdeath.wolf":"Твой Волчонок погиб от голода... Он выл на луну до последнего.",
"petdeath.dragon":"Твой Дракончик погиб от голода... Даже драконы нуждаются в заботе.",
"petdeath.phoenix":"Твой Феникс погиб от голода... Он не возродился. В этот раз — нет.",

// ===== АЧИВКИ =====
"ach.title":"🏆 Достижения","ach.filter_all":"Все","ach.filter_bronze":"🥉 Бронза",
"ach.filter_silver":"🥈 Серебро","ach.filter_gold":"🥇 Золото",
"ach.unlocked":"Разблокировано","ach.reward":"Награда",
"ach.new_ach":"🏆 Новое достижение","ach.plus_gems":"+{n} 💎",

// ===== ЗАДАНИЯ =====
"quests.title":"📜 Задания дня","quests.reset":"⏰ Сброс через",
"quests.claim":"🎁 Забрать награду","quests.not_done":"Ещё не выполнено",
"quests.claimed":"✅ Получено",
"quest.taps_100.name":"Сделай 100 тапов",
"quest.taps_500.name":"Сделай 500 тапов",
"quest.taps_1000.name":"Сделай 1000 тапов",
"quest.coins_10k.name":"Заработай 10K монет",
"quest.coins_100k.name":"Заработай 100K монет",
"quest.coins_1m.name":"Заработай 1M монет",
"quest.buy_upgrades_5.name":"Купи 5 улучшений",
"quest.open_chest.name":"Открой сундук",
"quest.catch_golden.name":"Поймай золотую монетку",
"quest.buy_skin.name":"Купи скин",
"quest.deposit_up.name":"Улучши вклад",
"quest.prestige_item.name":"Купи предмет за осколки",

// ===== ЛИДЕРЫ =====
"leaders.title":"🥇 Лидеры","leaders.submit_hint":"Твой ник закреплён за профилем. Отправить рекорд?",
"leaders.submit":"📤 Отправить рекорд","leaders.loading":"Загрузка...",
"leaders.empty":"Пока нет рекордов. Будь первым! 🏆",
"leaders.not_connected":"Лидерборд не подключён","leaders.sent":"✅ Рекорд отправлен!",

// ===== СКИНЫ =====
"skins.title":"🎨 Скины","skins.btn_title":"🖲️ Кнопка ТАП",
"skins.btn_hint":"Каждый скин — 5 💎","skins.emoji_title":"❤️ Эмодзи-скины",
"skins.emoji_hint":"По 10 💎. Кнопка превращается в эмодзи",
"skins.bg_title":"🖼️ Фон игры","skins.bg_hint":"По 25 💎. Тап — вкл/выкл",
"skins.smile_title":"🎭 Смайлик вклада","skins.smile_hint":"Только через промокод",
"skins.selected":"✓ Выбран","skins.active":"✓ Активен","skins.tap":"Нажмите",
"skins.promo_only":"Только промокод",
"skins.name_gold":"Золотистый","skins.name_blue":"Синий","skins.name_green":"Зелёный",
"skins.name_diamond":"Алмазный","skins.name_ruby":"Рубиновый","skins.name_gennadii":"GENNADII",
"skins.name_heart":"Сердечко","skins.name_fire_heart":"Огненное сердце",
"skins.name_shield":"Щит","skins.name_candy":"Конфета",
"skins.name_blood":"Кровавая мутация",

// ===== ФОНЫ =====
"bg.base":"Базовый","bg.space":"🌌 Космос","bg.flame":"🔥 Пламя","bg.ocean":"🌊 Океан",
"bg.sakura":"🌸 Сакура","bg.ice":"❄️ Лёд","bg.bloodmoon":"🌑 Кровавая луна",
"bg.volcano":"🌋 Вулкан","bg.nebula":"🌌 Туманность",

// ===== СТАТИСТИКА =====
"stats.title":"📊 Статистика","stats.coins_now":"Монет сейчас",
"stats.earned":"Всего заработано","stats.taps":"Тапов сделано",
"stats.cps":"Монет в секунду","stats.per_click":"За тап",
"stats.crystals":"Кристаллов","stats.shards":"Осколков",
"stats.shards_total":"Всего добыто 🌑","stats.time":"Время в игре",
"stats.ach":"Достижений","stats.record":"🏆 Личный рекорд",
"stats.minigame":"⏱️ Рекорд мини-игры","stats.taps_lower":"тапов",

// ===== НАСТРОЙКИ =====
"settings.title":"⚙️ Настройки","settings.language":"🌐 Язык",
"settings.float":"Показывать +N при тапе","settings.golden":"Показывать золотую монетку",
"settings.daily":"Ежедневный бонус","settings.sound":"Звуки","settings.music":"Музыка",
"settings.low_particles":"Меньше частиц","settings.krohlupic":"🐾 Показывать Крохлюпика",
"settings.promo_title":"🎁 Подарочный код","settings.promo_ph":"Введите код...",
"settings.promo_btn":"Активировать","settings.save_title":"💾 Сохранение прогресса",
"settings.export":"📤 Экспортировать прогресс",
"settings.export_hint":"Скопируйте этот код и сохраните себе.",
"settings.copy":"📋 Скопировать","settings.import":"📥 Импортировать прогресс",
"settings.import_hint":"Вставьте код, сохранённый ранее.",
"settings.import_ph":"Вставьте сюда код...","settings.import_load":"📥 Загрузить",
"settings.advanced":"🔧 Дополнительные настройки",
"settings.reset":"Сбросить весь прогресс",
"settings.reset_confirm":"⚠️ Весь прогресс будет удалён!\nПродолжить?",

// ===== КОНТАКТЫ =====
"contacts.title":"📞 Связь с разработчиком","contacts.tg":"Телеграм-канал",
"contacts.vk":"Канал ВКонтакте","contacts.support":"Связь с разработчиком",

// ===== АЛЬМАНАХ =====
"almanac.title":"📖 Альманах питомцев",
"almanac.subtitle":"Существа, которые могут присоединиться к Krochlupic-Up",
"almanac.chance":"Шанс выпадения",

// ===== ДРУЗЬЯ =====
"friends.title":"👥 Друзья","friends.my_id":"Твой ID для шаринга",
"friends.tab_list":"👥 Друзья","friends.tab_requests":"✉️ Заявки",
"friends.tab_search":"🔍 Найти","friends.no_friends":"Пока нет друзей. Найди по ID →",
"friends.incoming":"📥 Входящие","friends.no_incoming":"Нет входящих заявок",
"friends.outgoing":"📤 Исходящие","friends.no_outgoing":"Нет исходящих заявок",
"friends.search_hint":"Введи ID друга. Пример: <b>Artem#A4K2</b>",
"friends.online":"🟢 <b>{online}</b> из <b>{total}</b> онлайн",
"friends.status_online":"в сети","friends.status_away":"отошёл","friends.status_offline":"оффлайн",
"friends.was_online":"был {time} назад","friends.copy_id":"Копировать",
"friends.copied":"📋 Скопировано: {text}","friends.delete_confirm":"Удалить из друзей?",
"friends.gift_confirm":"Подарить 🎁 100 монет другу {name}?",
"friends.gift_sent":"🎁 +100 монет подарено другу!",
"friends.gift_already":"🎁 Ты уже дарил сегодня этому другу!",
"friends.gift_received":"🎁 Подарки: +{amount} монет от {senders}",
"friends.gift_no_coins":"Нужно минимум 100 монет для подарка!",

// ===== ЛС =====
"dm.title":"Сообщение","dm.placeholder":"Написать сообщение...",
"dm.hint":"Сообщения хранятся последние 100 штук","dm.loading":"Загрузка...",
"dm.empty":"Пока пусто. Напиши первым!","dm.loading_msgs":"Загрузка сообщений...",
"dm.send":"📤","dm.bad_word":"Сообщение содержит запрещённые слова",
"dm.too_fast":"Слишком часто! Подожди {t} сек.",
"dm.not_friend":"Этот игрок не у тебя в друзьях","dm.chat":"💬 Чат",
"dm.clear":"🗑 Очистить историю","dm.clear_confirm":"Очистить историю? У всех участников.",

// ===== СОРЕВНОВАНИЯ =====
"comp.tab":"🏁 Соревнования","comp.title":"Тапай-баттл",
"comp.subtitle":"Победитель получает +1% своего баланса.<br>Проигравший теряет −1% своего баланса.",
"comp.quick":"⚡ Быстрая игра","comp.quick_hint":"Случайный соперник · 10 сек",
"comp.create_title":"👥 Создать комнату","comp.create_btn":"🎮 Создать комнату",
"comp.join_title":"🔑 Вступить в комнату","comp.join_btn":"🚪 Вступить",
"comp.waiting":"⏳ Ожидание соперника...","comp.code_label":"Код комнаты:",
"comp.copy_code":"📋 Скопировать код","comp.copied":"✅ Скопировано!",
"comp.cancel":"✖ Отменить","comp.cancel_confirm":"Отменить комнату?",
"comp.leave_confirm":"Выйти из соревнования?","comp.vs":"VS",
"comp.win":"🏆 ПОБЕДА!","comp.lose":"💀 ПОРАЖЕНИЕ","comp.tie":"🤝 НИЧЬЯ",
"comp.your_taps":"Твои тапы","comp.opp_taps":"Тапы соперника",
"comp.reward_win":"💰 +{n} монет (1% баланса)","comp.reward_lose":"💸 −{n} монет (1% баланса)",
"comp.reward_tie":"Никто ничего не получает","comp.exit":"✖ Выйти","comp.close":"Закрыть",
"comp.you":"Я","comp.opponent":"???",

// ===== АУКЦИОН =====
"auction.tab":"🏪 Аукцион","auction.my_lots":"📦 Мои лоты","auction.market":"🏪 Рынок",
"auction.create":"➕ Выставить питомца","auction.create_title":"🏪 Выставить на аукцион",
"auction.hint":"Выбери питомца из хранилища и назначь цену в монетах",
"auction.commission":"Комиссия аукциона: 5%","auction.submit":"📤 Выставить лот",
"auction.buy":"Купить","auction.cancel":"✖","auction.empty_my":"У тебя нет активных лотов",
"auction.empty_market":"Лотов нет. Загляни позже!","auction.err_price":"Введи цену > 0",
"auction.err_storage_full":"Хранилище заполнено (5/5)",
"auction.err_no_coins":"Недостаточно монет",
"auction.confirm_buy":"Купить {pet} за {price} 💰?",
"auction.cancel_confirm":"Отменить лот и вернуть питомца?",

// ===== КЛАНЫ =====
"clan.tab_my":"🏰 Мой клан","clan.tab_search":"🔍 Поиск","clan.tab_create":"➕ Создать",
"clan.no_clan_text":"У тебя пока нет клана",
"clan.no_clan_hint":"Создай свой за 500 💎 или найди существующий",
"clan.btn_create":"➕ Создать клан","clan.btn_find":"🔍 Найти клан",
"clan.stat_members":"Участников","clan.stat_role":"Твоя роль",
"clan.sub_members":"👥 Участники","clan.sub_chat":"💬 Чат","clan.sub_requests":"✉️ Заявки",
"clan.chat_ph":"Написать сообщение...",
"clan.chat_hint":"Сообщения видны всем участникам клана",
"clan.no_requests":"Нет заявок","clan.btn_leave":"🚪 Выйти из клана",
"clan.btn_disband":"💀 Распустить клан","clan.search_ph":"Название или тег",
"clan.search_hint":"Введи название или тег клана","clan.field_name":"Название клана",
"clan.field_name_ph":"От 3 до 20 символов","clan.field_tag":"Тег (2–4 символа, A–Z)",
"clan.field_tag_ph":"KRL","clan.field_desc":"Описание",
"clan.field_desc_ph":"Коротко о клане...","clan.field_type":"Тип вступления",
"clan.type_open":"Открытый","clan.type_open_hint":"Вступают сразу",
"clan.type_closed":"Закрытый","clan.type_closed_hint":"По заявке",
"clan.create_cost":"Стоимость: 500 💎","clan.btn_create_submit":"🏗️ Создать клан за 500 💎",
"clan.role_owner":"👑 Владелец","clan.role_officer":"🛡 Офицер","clan.role_member":"👤 Участник",
"clan.btn_accept":"✓ Принять","clan.btn_decline":"✕","clan.btn_kick":"Кик",
"clan.btn_promote":"↑","clan.btn_demote":"↓",
"clan.kick_confirm":"Кикнуть игрока из клана?",
"clan.err_name_short":"Название должно быть от 3 до 20 символов",
"clan.err_tag_invalid":"Тег должен быть 2–4 латинские буквы",
"clan.err_tag_taken":"Такой тег уже занят",
"clan.err_not_enough_gems":"Недостаточно кристаллов (нужно 500 💎)",
"clan.err_in_clan":"Ты уже в клане","clan.err_chat_too_fast":"Не так быстро! Подожди пару секунд",
"clan.err_name_bad":"Название содержит недопустимые слова",
"clan.err_desc_bad":"Описание содержит недопустимые слова",
"clan.err_chat_bad":"Сообщение содержит недопустимые слова",
"clan.confirm_leave":"Выйти из клана?",
"clan.confirm_disband":"Распустить клан? Это действие необратимо!",
"clan.joined":"✅ Ты вступил в клан!","clan.request_sent":"✉️ Заявка отправлена",
"clan.left":"Ты вышел из клана","clan.disbanded":"Клан распущен",
"clan.full":"Клан заполнен (10 / 10)","clan.btn_edit":"✏️ Редактировать клан",
"clan.edit_title":"✏️ Редактировать клан","clan.edit_save":"💾 Сохранить изменения",
"clan.invest_title":"💰 Вложить в клан",
"clan.invest_hint":"Вложенные монеты повышают уровень клана<br>и дают <b>+1% к доходу</b> каждому участнику",
"clan.invest_custom":"Сколько монет вложить?\nУ тебя: {coins}",
"clan.invest_confirm":"Вложить {amount} монет в клан?",
"clan.invest_done":"🏰 Вложено {amount} в клан!",
"clan.invest_no_coins":"Недостаточно монет!\nНужно: {need}\nУ вас: {have}",

// ===== ПРОФИЛЬ =====
"profile.title":"🏅 Профиль","profile.hint":"Твой ник. Его нельзя будет изменить.",
"profile.nick_ph":"Твой ник","profile.save":"✅ Сохранить ник",
"profile.err_short":"Ник должен быть хотя бы 2 символа",
"profile.err_long":"Ник не длиннее 15 символов",
"profile.err_chars":"Только буквы, цифры, пробел и _","profile.err_empty":"Ник пустой",
"banner.title":"🎨 Баннер профиля",
"banner.hint":"Баннеры получаются за достижения, ивенты и уровни клана.",
"banner.new":"🎨 Новый баннер: {name}!",
"banner.novice.name":"🥉 Новичок","banner.novice.desc":"100 тапов",
"banner.farmer.name":"🌾 Фермер","banner.farmer.desc":"Заработать 1M монет",
"banner.veteran.name":"💠 Ветеран","banner.veteran.desc":"1T заработанных",
"banner.master.name":"👑 Мастер","banner.master.desc":"50 достижений",
"banner.legend.name":"🌟 Легенда","banner.legend.desc":"Топ-1 лидерборда",
"banner.absolute.name":"🔱 Абсолют","banner.absolute.desc":"Абсолют 699 ур.",
"banner.genesis.name":"💠 Генезис","banner.genesis.desc":"7 питомцев",
"banner.bloodlord.name":"🩸 Кровавый Лорд","banner.bloodlord.desc":"10 побед в сорев.",

// ===== ОБУЧЕНИЕ =====
"tutorial.next":"Далее ▶","tutorial.skip":"Пропустить ✕","tutorial.finish":"Завершить ✓",
"tutorial.1":"👆 Нажми на большую кнопку — получишь монеты",
"tutorial.2":"🛒 Покупай улучшения в Магазине — доход идёт сам",
"tutorial.3":"⚡ Прокачивай генератор, чтобы тапать чаще!",
"tutorial.4":"🎁 Раз в час открывай Сундук — там кристаллы и осколки",
"tutorial.5":"📜 Выполняй ежедневные Задания — обновляются каждый день",
"tutorial.6":"🎨 Покупай Скины и заглядывай в Магазин за 💎",
"tutorial.7":"🐾 На второй странице — Питомцы. Собирай и корми!",
"tutorial.8":"🕵️ В игре есть немало секретных действий — попробуй их найти!",

// ===== ЗАПИСКИ =====
"note.title":"📜 Записки","note.found":"Найденные записки","note.back":"← Назад к списку",
"note.empty":"Пока нет записок. Их можно найти в игре…","note.new":"📜 Записка появилась...",
"note.note1.title":"Записка №1",
"note.note1.text":"«Он заставляет меня нажимать эту чёртову кнопку. Я устал. Сутки напролёт я сижу здесь и нажимаю её — ради денег. Лишь это поможет…»",
"note.note2.title":"Записка №2",
"note.note2.text":"«Сначала.. Как по мне, всё выглядит красиво, и.. Так правильно, столько существ объединились.. Но мне не даёт покоя один факт, зачем это всё, в чем смысл такого бизнеса?»",
"note.note3.title":"Записка №3",
"note.note3.text":"«Дорогой дневник, я наконец-то нашел работу!\nЭта студия самая богатая в этом городе, и.. подозреваю что в этом мире!»",
"note.note4.title":"Записка №4",
"note.note4.text":"«Я {NICK} соглашаюсь с условиями и вступаю в компанию Krochlupic-Up!»",
"note.note5.title":"Записка №5",
"note.note5.text":"«Дорогой дневник, знаю это глупо, но... Хотя, зачем мне делиться своими переживаниями с бумажкой?»",
"note.note6.title":"Записка №6",
"note.note6.text":"«Он такой милый, никогда не видел рас, которые были такими очаровательными!»",
"note.note7.title":"Записка №7",
"note.note7.text":"«Я слышал крик, у выхода из здания, вчера.. а сегодня.. он пропал.. его похитили! Это точно!»",
"note.sign.contract":"— Контракт","note.sign.unknown":"— ???",

// ===== АДМИНКА =====
"admin.title":"👑 Админ-консоль",
"admin.hint":"Команды применяются ко <b>всем игрокам</b> сервера",
"admin.status_boost":"🟢 Онлайн-буст:","admin.status_event":"🎉 Активный ивент:",
"admin.no":"нет","admin.history":"📜 История команд","admin.no_history":"История пуста",
"admin.err_no_access":"❌ Нет доступа","admin.err_unknown_cmd":"❌ Неизвестная команда. Напиши help",
"admin.ok":"✅ Готово","admin.confirm_gift":"Отправить подарок всем игрокам?",
"admin.confirm_boost":"Включить глобальный буст для всех?",
"admin.confirm_event":"Запустить глобальный ивент для всех?",
"admin.gift_sent":"🎁 Подарки отправлены всем игрокам",
"admin.boost_started":"⚡ Глобальный буст активирован","admin.boost_stopped":"⚡ Глобальный буст выключен",
"admin.event_started":"🎉 Ивент запущен","admin.event_stopped":"🎉 Ивент остановлен",
"admin.message_sent":"📢 Сообщение отправлено",
"admin.promo_unlocked":"🔓 Админ-функция разблокирована. Зайди в Настройки → Дополнительные.",
"admin.pass_prompt":"🔑 Введите пароль:","admin.pass_wrong":"❌ Неверный пароль",
"admin.hidden_btn":"🔐 Скрытые настройки",

// ===== FNF =====
"fnf.title":"🥊 БИТВА С КРОХЛЮПИКОМ","fnf.hp":"❤️ Жизни","fnf.seconds_left":"сек",
"fnf.start":"▶️ Начать битву",
"fnf.start_hint":"Стрелки летят вниз — тапай их в такт!",
"fnf.cooldown":"⏳ Следующая битва через","fnf.cooldown_ready":"Готов к битве!",
"fnf.win":"🏆 ПОБЕДА!","fnf.lose":"💀 ПОРАЖЕНИЕ",
"fnf.win_text":"Ты продержался до конца!\n\n🎵 Счёт: {score}\n❌ Промахи: {miss}\n🔥 Макс. комбо: {combo}×\n\nНаграда:\n{rewards}",
"fnf.lose_text":"Крохлюпик победил...\n\n🎵 Счёт: {score}\n❌ Промахи: {miss}\n🔥 Макс. комбо: {combo}×",
"fnf.perfect":"🌟 ИДЕАЛЬНО! Бонус ×2!",
"fnf.reward_gems":"💎 +{n} кристаллов","fnf.reward_shards":"🌑 +{n} осколков",
"fnf.reward_coins":"🪙 +{n} монет","fnf.err_already":"Битва уже идёт!",
"fnf.err_cooldown":"Рано! Следующая битва через {t}",

// ===== СУНДУК / КОЛЕСО / ЕЖЕДНЕВКА / МИНИ-ИГРА =====
"chest.collect":"✅ Забрать",
"wheel.title":"🎡 Колесо фортуны","wheel.spin_free":"🎁 Крутить бесплатно",
"wheel.spin_paid":"💰 Крутить","wheel.free_used":"🎁 Завтра",
"wheel.free_used_alert":"Бесплатный спин уже использован!","wheel.paid_used":"💰 Завтра",
"wheel.paid_used_alert":"Платный спин уже использован!",
"wheel.no_coins":"Недостаточно монет!\nНужно: {need}",
"wheel.result_coins":"💰 Получено {n} монет!","wheel.result_gems":"💎 +{n} кристаллов!",
"wheel.result_shards":"🌑 +{n} осколков!","wheel.result_negcoins":"💀 Потеряно {n} монет!",
"wheel.result_neggems":"💀 −{n} кристаллов!","wheel.result_negshards":"💀 −{n} осколков!",
"wheel.result_empty":"❌ Пусто. В следующий раз повезёт!",
"wheel.timer_tomorrow":"Следующие спины — завтра в 9:00",
"wheel.timer_available":"1 бесплатный + 1 платный спин в день",
"wheel.timer_paid":"Доступен платный спин",
"wheel.spin_for":"Крутить за","wheel.first_free":"Сначала бесплатный",
"daily.title":"📅 Ежедневная награда","daily.hint":"Крути рулетку раз в день!",
"daily.spin":"🎁 Крутить!","daily.already":"Сегодня уже крутил! Завтра снова.",
"daily.done_today":"Сегодня получено",
"daily.timer":"Следующая награда — завтра в 9:00",
"daily.timer_tomorrow":"Следующая награда — завтра в 9:00",
"daily.timer_today":"1 бесплатный спин в день!",
"daily.result_coins":"💰 Получено {n} монет!","daily.result_gems":"💎 +{n} кристаллов!",
"daily.result_shards":"🌑 +{n} осколков!",
"daily.result_boost":"⚡ Бустер ×{n} добавлен в хранилище!",
"minigame.title":"⏱️ Мини-игра: 10 секунд",
"minigame.hint":"Тапни как можно больше раз!","minigame.tap_btn":"👆 ТАП!",
"minigame.taps":"Тапов","minigame.best":"Рекорд","minigame.start":"▶️ Начать",
"minigame.restart":"🔁 Ещё раз","minigame.playing":"⏳ Играем...",
"minigame.ready":"Можно играть!","minigame.next":"Следующая игра через",
"minigame.too_early":"Рано! Следующая игра через {t}",
"minigame.result_new":"🎉 НОВЫЙ РЕКОРД! {taps} тапов! +{reward} 💎",
"minigame.result":"Тапов: {taps}. {reward}","minigame.result_reward":"Награда: +{n} 💎",
"minigame.result_try":"Попробуй ещё!",

// ===== ГЕНЕРАТОР =====
"generator.title":"⚡ Генератор кнопки","generator.level":"Уровень {n} / {max}",
"generator.level_word":"Уровень","generator.level_short":"Ур",
"generator.speed":"Скорость:","generator.speed_label":"Скорость:",
"generator.drop_in":"До падения:",
"generator.warning":"⚠️ Раз в 3 минуты уровень падает на 1–5",
"generator.warning_line":"⚠️ Раз в 3 минуты уровень падает на 1–5",
"generator.upgrade":"Улучшить:","generator.upgrade_btn":"⚡ Улучшить",
"generator.upgrade_btn_short":"Улучшить","generator.upgrade_price":"Улучшить:",
"generator.max":"✨ Максимальный уровень!","generator.max_line":"✨ Максимальный уровень!",
"generator.drop":"⚡ Генератор упал на {n} ур. (сейчас {level})",
"generator.no_coins":"Недостаточно монет!\nНужно: {need}\nУ вас: {have}",
"generator.tap_per_sec":" тап/сек","generator.tap_per_sec_plural":" тапов/сек",
"generator.tap_in_sec":"1 тап за ",

// ===== ВКЛАД =====
"deposit.title":"🏦 Вклад",
"deposit.buy_hint":"Купите вклад за <b>1 Qa</b> монет, чтобы открыть смайлика.",
"deposit.buy_hint2":"Смайлик будет расти с каждым вложением.",
"deposit.buy_line":"Купите вклад за <b>1 Qa</b> монет, чтобы открыть смайлика.",
"deposit.grow_hint":"Смайлик будет расти с каждым вложением.",
"deposit.buy_btn":"Купить вклад за 1 Qa",
"deposit.level":"Уровень {n} / 25","deposit.level_word":"Уровень",
"deposit.hungry":"😭 Голодный! Ест 5M монет в секунду",
"deposit.hungry_line":"😭 Голодный! Ест 5M монет в секунду",
"deposit.full":"✨ Полный вклад! Смайлик сыт и доволен.",
"deposit.full_line":"✨ Полный вклад! Смайлик сыт и доволен.",
"deposit.happy":"Смайлик доволен","deposit.happy_line":"Смайлик доволен",
"deposit.next":"Следующий уровень:","deposit.next_line":"Следующий уровень:",
"deposit.invest_btn":"💰 Вложить","deposit.max_reached":"Достигнут максимум!",
"deposit.drop":"😭 Смайлик упал: {from} → {to}",

// ===== БОСС =====
"boss.title":"💀 БОСС-СМАЙЛИК","boss.hint":"Тапай по боссу! Успей за 45 секунд.",
"boss.start":"🔥 Начать бой","boss.again":"🔁 Ещё раз","boss.retry":"🔁 Попробовать снова",
"boss.win":"🏆 Победа! +25 🌑 кровавых осколков!",
"boss.win_again":"🏆 Победа! (награда уже получена ранее)",
"boss.lose":"💀 Провал! −{lost} монет.",

// ===== НАГРАДА / ТРЕВОГА =====
"reward.title":"🏅 Награда","reward.desc":"Вы прокачали Кликер до 228 уровня!",
"reward.sub":"За это полагается особая награда.","reward.claim":"🎁 Забрать награду",
"reward.claimed":"🎉 Ты получил +25 🌑 кровавых осколков!",
"reward.tab_msg":"🏅 Ты прокачал Кликер до 228! Открой вкладку «Награда»!",
"alarm.text":"Ты давно не тапал!<br>Нажми на знак 5 раз",

// ===== ПОМОЩЬ =====
"help.title":"❓ Как играть",
"help.1":"<b>1.</b> Тапайте по большой кнопке — получаете монеты.",
"help.2":"<b>2.</b> Покупайте улучшения в магазине.",
"help.3":"<b>3.</b> Золотая монетка даёт x7 на 30 секунд.",
"help.4":"<b>4.</b> За достижения даются 💎 (🥉=1, 🥈=3, 🥇=5).",
"help.5":"<b>5.</b> Сундук раз в час — кристаллы, монеты, осколки, бустеры.",
"help.6":"<b>6.</b> Оффлайн-доход до 8 часов.",
"help.7":"<b>7.</b> Скины кнопки за 5 💎, эмодзи за 10 💎, фоны за 25 💎.",
"help.8":"<b>8.</b> Предметы за 🌑 — 3 уровня.",
"help.9":"<b>9.</b> Вклад — смайлик, каждые 30 минут падает уровень.",
"help.10":"<b>10.</b> Генератор — прокачивает скорость тапов.",
"help.11":"<b>11.</b> Лидерборд — рейтинг по «Всего заработано».",
"help.12":"<b>12.</b> Задания обновляются в 6:00.",
"help.13":"<b>13.</b> 🐾 Питомцы — покупай яйца, корми, получай бонусы.",
"help.14":"<b>14.</b> Активный питомец должен быть сыт, иначе погибнет!",
"help.15":"<b>15.</b> 🌪️ Кровавый Шторм — каждый понедельник 9:00!",
"help.16":"<b>16.</b> 👥 Друзья — шарь свой ID, добавляй в друзья, следи за онлайном!",
"help.17":"<b>17.</b> 🏰 Кланы — создай свой за 500 💎 или вступи в существующий!",
"help.18":"<b>18.</b> 🥊 FNF-битва — тапай стрелки в такт музыке!",

// ===== ИВЕНТЫ =====
"event.rain":"💰 Монетный дождь","event.storm":"⚡ Молниеносный потенциал",
"event.fast":"🏃 Быстрый способ","event.income":"💵 Заработок",
"event.super_storm":"🌪️ КРОВАВЫЙ ШТОРМ!",
"event.blood_moon":"🌕 КРОВАВАЯ ЛУНА 🌕\nДоход x2!",
"event.theft_start":"🚨 Ивент «КРАЖА» начался! Потеряно будет ~22% монет.",
"event.theft_end":"🚨 Кража закончилась. Всего украдено: {n} монет",

// ===== СЕКРЕТ =====
"secret.title":"⚡ Кликер 67","secret.subtitle":"Секретный автокликер",
"secret.desc":"Делает 67 кликов в секунду автоматически.",
"secret.unlock_hint_1":"Для разблокировки нужно сделать",
"secret.taps_word":"тапов","secret.your_taps":"У вас",
"secret.unlock_btn":"🔒 Разблокировать",
"secret.unlocked_ok":"✅ Автокликер разблокирован!",
"secret.activate":"🔥 Активировать (67 Qa)",
"secret.activate_again":"🔥 Активировать ещё (67 Qa)",
"secret.status_default":"Разблокирован. Активация: 67 Qa за 30 минут.",
"secret.active":"🔥 Автокликер активен — 67 кликов/сек. Осталось: {time}",
"secret.too_early":"❌ Ещё рано!\nНужно {need} тапов.\nОсталось: {left}",
"secret.no_coins":"❌ Нужно 67 Qa!","secret.unlocked":"🔥 Кликер 67 разблокирован!",
"secret.stopped":"⏸️ Кликер 67 остановлен.",

// ===== ПРОМО =====
"promo.enter_code":"Введите код.","promo.used":"Этот код уже использован.",
"promo.invalid":"Неверный код.",

// ===== БУСТЕРЫ =====
"booster.boost2":"Буст ×2","booster.boost2.desc":"Множитель ×2 на 15 минут",
"booster.boost3":"Буст ×3","booster.boost3.desc":"Множитель ×3 на 10 минут",
"booster.boost5":"Буст ×5","booster.boost5.desc":"Множитель ×5 на 5 минут",
"booster.activate_btn":"Активировать","booster.none":"Нет в наличии",
"booster.other_active":"Активен другой","booster.already":"Уже активен",
"booster.in_stock":"В наличии","booster.active_label":"Активен",
"booster.left_label":"осталось",

// ===== КРИСТАЛЛ-МАГАЗИН =====
"crystal.coinsBag":"Мешок монет","crystal.coinsBag.desc":"1 час дохода монетами",
"crystal.boost2":"Буст ×2","crystal.boost2.desc":"Множитель ×2 на 15 минут → в хранилище",
"crystal.boost3":"Буст ×3","crystal.boost3.desc":"Множитель ×3 на 10 минут → в хранилище",
"crystal.boost5":"Буст ×5","crystal.boost5.desc":"Множитель ×5 на 5 минут → в хранилище",
"crystal.chest":"Мгновенный сундук","crystal.chest.desc":"Сразу открывает сундук",
"crystal.depositUp":"+1 уровень вклада","crystal.depositUp.desc":"Только если вклад куплен",
"crystal.in_storage":"В хранилище:","crystal.will_give":"Даст",
"crystal.cps_zero":"CPS пока 0","crystal.buy_deposit_first":"Сначала купите вклад",
"crystal.deposit_max":"Вклад на максимуме","crystal.level_short":"Ур.",
"crystal.will_open":"Сразу откроется",

// ===== ПРЕДМЕТЫ / УЛУЧШЕНИЯ =====
"item.not_bought":"Не куплено · Ур. 0/3","item.max":"Максимум · Ур. 3/3",
"item.level_short":"Ур.","item.upgrade_short":"Улучшить",
"up.max":"✓ Максимум","up.max_short":"Максимум","up.buy_short":"Купить",
"up.buy":"Купить ×{mult}","up.bought":"Куплено:","up.level_label":"Уровень:",
"up.unlock10":"🔒 {price}💎","up.unlock25":"🔒 {price}💎",
"up.unlock10_confirm":"Разблокировать ×10 за {price} 💎?",
"up.unlock25_confirm":"Разблокировать ×25 за {price} 💎?",

// ===== ГЛОБАЛЬНЫЕ УЛУЧШЕНИЯ =====
"globalup.superClicker":"🌟 Супер кликер",
"globalup.superClicker.desc":"+1 к базовому клику за уровень",
"globalup.bloodLuck":"🩸 Кровавая удача",
"globalup.bloodLuck.desc":"+1% к шансу кровавого осколка в Кровавую луну",
"globalup.absoluteBoost":"🔱 Воля Абсолюта",
"globalup.absoluteBoost.desc":"+5% к прибыли от Абсолюта",
"globalup.genesisBoost":"💠 Эхо Генезиса",
"globalup.genesisBoost.desc":"+3% к прибыли от Генезиса",
"globalup.inactive":"Сейчас: не активно",
"globalup.now_click":"Сейчас: +","globalup.now_chance":"Сейчас: +",
"globalup.now_income":"Сейчас: +",

// ===== УЛУЧШЕНИЯ =====
"up.clicker":"👆 Кликер","up.clicker.desc":"+1 монета за тап",
"up.farm":"🌾 Ферма","up.farm.desc":"+1 монета в секунду",
"up.factory":"🏭 Фабрика","up.factory.desc":"+10 монет в секунду",
"up.bank":"🏦 Банк","up.bank.desc":"+100 монет в секунду",
"up.server":"🖥️ Серверная","up.server.desc":"+1000 монет в секунду",
"up.lab":"🔬 Лаборатория","up.lab.desc":"+10000 монет в секунду",
"up.space":"🚀 Космостанция","up.space.desc":"+100K монет в секунду",
"up.quantum":"⚛️ Квантовый комп","up.quantum.desc":"+1M монет в секунду",
"up.portal":"🌀 Портал","up.portal.desc":"+10M монет в секунду",
"up.galaxy":"🌌 Галактика","up.galaxy.desc":"+100M монет в секунду",
"up.universe":"🌠 Вселенная","up.universe.desc":"+1B монет в секунду",
"up.multiverse":"♾️ Мультивселенная","up.multiverse.desc":"+10B монет в секунду",
"up.singularity":"🕳️ Сингулярность","up.singularity.desc":"+100B монет в секунду",
"up.godmode":"👁️ Око Творца","up.godmode.desc":"+1T монет в секунду",
"up.infinity":"💫 Бесконечность","up.infinity.desc":"+10T монет в секунду",
"up.timecrystal":"🕰️ Кристалл времени","up.timecrystal.desc":"+100T монет в секунду",
"up.blackhole":"🌑 Чёрная дыра","up.blackhole.desc":"+1Qa монет в секунду",
"up.omega":"♎ Омега","up.omega.desc":"+10Qa монет в секунду",
"up.eternity":"🌌 Вечность","up.eternity.desc":"+100Qa монет в секунду",
"up.creation":"✨ Творец","up.creation.desc":"+2Qi монет в секунду",
"up.absolute":"🔱 Абсолют","up.absolute.desc":"+20Qi монет в секунду",
"up.transcend":"🕉️ Трансцендентность","up.transcend.desc":"+60Qi монет в секунду",
"up.genesis":"💠 Генезис","up.genesis.desc":"+500Qi монет в секунду",

// ===== ПРЕДМЕТЫ =====
"item.blade":"Кровавый клинок","item.blade.desc":"Оружие первых охотников",
"item.amulet":"Амулет луны","item.amulet.desc":"Оберег из чёрного камня",
"item.elixir":"Кровавый эликсир","item.elixir.desc":"Зелье из лунной росы",
"item.candle":"Свеча ритуала","item.candle.desc":"Горит вечно алым светом",
"item.skull":"Череп врага","item.skull.desc":"Трофей с поля битвы",
"item.bat":"Летучая мышь","item.bat.desc":"Хранительница ночи",
"item.orb":"Тёмный шар","item.orb.desc":"Видит сквозь время",
"item.scythe":"Серп луны","item.scythe.desc":"Жнёт врагов как колосья",
"item.wings":"Крылья вампира","item.wings.desc":"Дар ночной охоты",
"item.crown":"Венец луны","item.crown.desc":"Власть над Кровавой луной",
"item.throne":"Трон Кровавого Лорда","item.throne.desc":"Легендарный трон алой эпохи",

// ===== ПРЕДСКАЗАНИЯ =====
"fortune.label":"Печенька говорит:","fortune.close":"Спасибо, печенька!",
"fortune.1":"Сегодня удача на твоей стороне. Тапай смелее!",
"fortune.2":"Один тап — и мир изменится. Может, именно этот?",
"fortune.3":"Смайлик сегодня доволен тобой. Не подведи его.",
"fortune.4":"Хороший день для покупки улучшений.",
"fortune.5":"Если что-то не получается — просто тапай ещё.",
"fortune.6":"Кровавая луна знает о тебе больше, чем ты думаешь.",
"fortune.7":"Он смотрит. Он всегда смотрит.","fortune.8":"Кристаллы приходят к терпеливым.",
"fortune.9":"Сегодня ты найдёшь то, что давно искал.",
"fortune.10":"Не все кликеры одинаково полезны. Некоторые — судьба.",
"fortune.11":"Записки — не просто текст. Это предупреждение.",
"fortune.12":"Ты слишком много тапаешь. Но это не точно.",
"fortune.13":"Пахан одобряет твой выбор.",
"fortune.14":"Иногда лучший ход — остановиться. Но не сегодня.",
"fortune.15":"Сегодня хороший день для рекорда.",
"fortune.16":"Твой смайлик мечтает о 25 уровне.",
"fortune.17":"Кровавые осколки любят настойчивых.",
"fortune.18":"Если увидишь золотую монетку — не зевай.",
"fortune.19":"Один клик отделяет тебя от величия.",
"fortune.20":"Сегодня можно всё. Даже купить скин.",
"fortune.21":"Тайна ближе, чем кажется. Просто копай глубже.",
"fortune.22":"Не забывай про сундук. Он ждёт.",
"fortune.23":"Что-то хорошее случится через 67 тапов.",
"fortune.24":"Сегодня звезда по имени Ты восходит.",
"fortune.25":"Мир — это кликер. Ты — его игрок.",
"fortune.26":"Слушай музыку. Она знает ритм удачи.",
"fortune.27":"Не все секреты нужно искать. Некоторые найдут тебя.",
"fortune.28":"Сегодня никто не догонит тебя в лидерборде.",
"fortune.29":"День, когда сбывается загаданное на 228 тапе.",
"fortune.30":"Улыбнись смайлику — и он улыбнётся тебе.",
"fortune.31":"Тот, кто читает это, уже победитель.",
"fortune.32":"Два клика — и ты ближе к цели.",
"fortune.33":"Жизнь как сундук: откроешь — узнаешь.",
"fortune.34":"Кристаллы — это застывшее время. Береги их.",
"fortune.35":"Сегодня лучше, чем вчера. И это факт.",
"fortune.36":"Кто-то наблюдает за твоими успехами. Продолжай.",
"fortune.37":"Хорошее предсказание всегда сбывается. Это — хорошее.",
"fortune.38":"Не всё золото, что блестит. Но монетка точно твоя.",

// ===== СОЦИАЛЬНОЕ =====
"social.online":"🟢 <b>{online}</b> из <b>{total}</b> онлайн",
"social.was_online":"был {time} назад","social.copy_success":"📋 Скопировано: {text}",
"social.gift_sent":"🎁 +100 монет подарено другу!",
"social.gift_received":"🎁 Подарки: +{amount} монет от {senders}",

// ===== ПОДПИСКА =====
"subscribe.title":"Подпишись на наши каналы!",
"subscribe.sub":"Там много полезного: новости, обновления, ивенты",
"subscribe.ok":"✅ Понятно",

// ===== РЕПЛИКИ КРОХЛЮПИКА =====
"khrquote.coins_100":"Смотри, у нас уже 100! Это начало чего-то большого.",
"khrquote.coins_1k":"1 000 монет! Я так горд. Правда. Я серьёзно.",
"khrquote.coins_100k":"100K? Эй, а ты быстро растёшь!",
"khrquote.coins_1m":"Миллион! Похоже, ты и вправду справишься.",
"khrquote.coins_1b":"Миллиард. Знаешь, у нас даже стулья в офисе появились!",
"khrquote.coins_1t":"Триллион… Неловко спрашивать, но это ведь много?",
"khrquote.coins_1qa":"Квадриллион! Ты когда-нибудь спишь?",
"khrquote.coins_1qi":"Квинтиллион. Я даже произносить это боюсь.",
"khrquote.coins_1sp":"Я думал, мы никогда не дойдём. А ты взял — и дошёл.",
"khrquote.coins_1no":"Но... Как... Это же цифра, которой не должно быть на балансе. Ох.",
"khrquote.taps_10":"Раз, два, три... Ой, я не успеваю считать!",
"khrquote.taps_100":"Ты так стараешься. Я это ценю.",
"khrquote.taps_1k":"У тебя палец не болит? Мой бы болел.",
"khrquote.taps_10k":"10 000! Ты машина, что ли?",
"khrquote.taps_100k":"У меня лапки устали смотреть.",
"khrquote.taps_1m":"Миллион тапов. Я даже не знаю, что сказать.",
"khrquote.up_farm":"Ферма! Теперь монеты идут сами. Удобно!",
"khrquote.up_factory":"Фабрика работает. Мы расширяемся, знаешь?",
"khrquote.up_bank":"Банк! Скоро будем брать кредиты.",
"khrquote.up_space":"Космос! Я слышал, там есть другие кликеры.",
"khrquote.up_galaxy":"Ого. Ты строишь не бизнес, а вселенную.",
"khrquote.up_genesis":"Генезис… Это начало. Или конец? Я не уверен.",
"khrquote.ach_first":"Достижение! Ты молодец. Серьёзно.",
"khrquote.ach_50":"Половина достижений! Ты упорный.",
"khrquote.ach_all":"Ты... собрал всё. Я горд. И немного напуган.",
"khrquote.ev_theft_start":"Кража! Прячь монеты! Скорее!",
"khrquote.ev_theft_end":"Фух. Обошлось. Кажется.",
"khrquote.ev_bloodmoon":"Смотри, луна красная! Доход ×2, но будь осторожен.",
"khrquote.note_found":"Ещё одна записка? Кто их пишет?..",
"khrquote.cute_1":"Я тут подумал... ты хороший.",
"khrquote.cute_2":"Иногда мне нравится просто смотреть, как ты тапаешь.",
"khrquote.cute_3":"У тебя отличный вкус на апгрейды, знаешь?",
"khrquote.cute_4":"Мне нравится быть с тобой в одной команде.",
"khrquote.cute_5":"Заяц-программист из меня так себе, но я стараюсь.",
"khrquote.strange_1":"Слушай... а ты помнишь, откуда я появился? Я — нет. Странно.",
"khrquote.strange_2":"Иногда мне кажется, что за тобой наблюдают. Но это, наверное, ничего.",
"khrquote.strange_3":"Я вчера слышал звук. Такой, знаешь... будто кто-то тапает не здесь.",
"khrquote.strange_4":"Тот, из записок. Он был тут раньше. Я его почти помню.",
"khrquote.strange_5":"Если я однажды исчезну — не ищи меня. Просто продолжай тапать.",
"khrquote.strange_6":"Кажется, эта кнопка никогда не заканчивается. Никогда. Понимаешь?",
"khrquote.strange_7":"Не заходи в комнату 9. Ой. Забудь, что я сказал.",
"khrquote.back_1":"Ты вернулся! А я уже думал, что меня одного здесь оставили.",
"khrquote.back_2":"Ой! Привет. Я тут сидел, смотрел на кнопку. Она красивая.",
"khrquote.back_3":"Ты долго не заходил. Я скучал. И монеты скучали.",

// ===== ALERT-СООБЩЕНИЯ =====
"alert.not_enough_coins":"❌ Недостаточно монет!\nНужно: {0}\nУ вас: {1}",
"alert.not_enough_crystals":"❌ Недостаточно кристаллов!\nНужно: {0}\nУ вас: {1}",
"alert.not_enough_shards":"❌ Недостаточно осколков!\nНужно: {0}\nУ вас: {1}",
"alert.not_enough_xp":"❌ Недостаточно опыта!",
"alert.promo_only":"🎁 Только через промокод!",
"alert.booster_active":"⚡ Буст уже активен, дождись окончания!",
"alert.booster_none":"📦 Нет бустеров в наличии!",
"alert.offline_coins":"💰 Получено {0} монет!",
"alert.export_empty":"❌ Нет сохранения для экспорта.",
"alert.export_error":"❌ Ошибка экспорта: {0}",
"alert.export_copied":"✅ Скопировано!",
"alert.export_copy_fail":"❌ Не удалось скопировать. Выдели текст и скопируй вручную.",
"alert.import_empty":"❌ Вставь код сохранения.",
"alert.import_bad_format":"❌ Неверный формат сохранения.",
"alert.import_confirm":"⚠️ Текущий прогресс будет заменён.\nПродолжить?",
"alert.import_loaded":"✅ Прогресс загружен! Перезагрузка...",
"alert.import_error":"❌ Ошибка импорта: {0}",
"alert.daily_bonus":"📅 Ежедневный бонус! День {0} подряд.\n+{1} монет!",
"alert.daily_bonus_week":"🎁 +5 💎 за 7 дней подряд!",
"alert.leaderboard_no_firebase":"❌ Лидерборд не подключён.",
"alert.leaderboard_no_nick":"❌ Сначала задай ник в профиле!",
"alert.set_nickname":"❌ Сначала задай ник в профиле!",
"alert.pet_storage_full":"❌ Хранилище заполнено (5/5)!",
"alert.pet_nest_busy":"❌ Гнездо занято! Дождись завершения.",
"alert.deposit_buy_first":"❌ Сначала купите вклад в модалке смайлика!",
"alert.deposit_max":"❌ Вклад уже на максимуме (25 ур.)!",
"alert.competition_room_taken":"❌ Комната уже занята!",
"alert.competition_not_found":"❌ Комната не найдена!",
"alert.competition_wrong_code":"❌ Код должен быть 4 символа!",
"alert.fnf_already":"❌ Битва уже идёт!",
"alert.fnf_cooldown":"⏳ Рано! Следующая битва через {0}"
},
 en:{
// ===== COMMON =====
"common.close":"✕ Close","common.close_x":"✖ Close","common.cancel":"✖ Cancel",
"common.ok":"✅ OK","common.yes":"Yes","common.no":"No","common.error":"Error",
"common.loading":"Loading...",
"common.seconds_short":" s","common.minutes_short":" min","common.hours_short":" h ",
"common.coins_word":"coins",

// ===== TABS =====
"tab.items":"🛒 Shop","tab.boosters":"📦 Boosters","tab.achievements":"🏆 Achievements",
"tab.quests":"📜 Quests","tab.leaders":"🥇 Leaders","tab.friends":"👥 Friends",
"tab.skins":"🎨 Skins","tab.stats":"📊 Stats","tab.settings":"⚙️ Settings",
"tab.help":"❓ Help","tab.reward":"🏅 Reward","tab.note":"📜 Note",

// ===== MAIN =====
"main.coins":"coins","main.per_second":"Per second",
"main.hungry":"😭 Hungry smiley: −5M coins/sec",
"main.gulau_mult":"×5 taps, left","main.crystals":"💎 Crystals",
"main.blood_moon":"🌕 Blood Moon! Ends in","main.shards":"🌑 Blood shards",
"main.bonus":"⚔️ Bonus","main.tap":"TAP",
"main.generator":"⚡ Generator: Lvl 1","main.generator_word":"Generator",
"main.chest":"🎁 Chest","main.wheel":"🎡 Fortune","main.daily":"📅 Daily",
"main.minigame":"⏱️ Mini-game","main.fnf":"🥊 Battle with Krohlupic",
"main.fortune":"🥠 Fortune cookie","main.fortune_wait":"🥠 Tomorrow",
"main.shop_title":"Upgrades Shop","main.shop_upgrades":"Upgrades",
"main.shop_global":"Global upgrades",
"season.rating":"Season rating","season.left":"Days left",

// ===== PETS =====
"pets.title":"🐾 PETS","pets.buy_egg":"🥚 Buy egg — 65 💎",
"pets.tap_3":"👆 Tap 3 times!","pets.tap_collect":"👆 Tap to collect!",
"pets.storage":"📦 STORAGE","pets.empty":"Empty",
"pets.active_title":"⭐ ACTIVE PET","pets.no_active":"No active pet",
"pets.hunger":"🍽️ Hunger","pets.deactivate":"↩️ Move to storage",
"pets.food_shop_title":"🛒 FOOD SHOP",
"pets.food_hunger_5":"+5 hunger","pets.food_hunger_10":"+10 hunger",
"pets.food_hunger_20":"+20 hunger",
"pets.buy":"Buy","pets.feed":"Feed","pets.activate":"Activate",
"pets.sell":"Sell",
"pets.rarity_common":"🟢 Common","pets.rarity_rare":"🔵 Rare",
"pets.rarity_epic":"🟣 Epic","pets.age":"Age",
"pets.feed_success":"✅ Pet fed!","pets.feed_no_food":"❌ No such food!",
"pets.pet_died":"💀 Your {pet} starved to death...",
"pets.no_money_food":"❌ Not enough ⭐ to buy food!",
"pets.storage_full":"Storage is full (5/5)!",
"pets.name_hamster":"Hamster","pets.name_kitten":"Kitten","pets.name_fox":"Fox cub",
"pets.name_penguin":"Penguin","pets.name_wolf":"Wolf cub","pets.name_dragon":"Dragon",
"pets.name_phoenix":"Phoenix",
"pet.bonus_income":"% income","pet.bonus_gem":"% gem","pet.bonus_shard":"% shard",
"pet.sell_price":"Sell price","pet.egg_chance":"Egg chance",

// ===== PET DEATHS =====
"petdeath.hamster":"Your Hamster starved to death... He was a faithful friend.",
"petdeath.kitten":"Your Kitten starved to death... He purred to the very end.",
"petdeath.fox":"Your Fox cub starved to death... Cunning, but hungry.",
"petdeath.penguin":"Your Penguin starved to death... He didn't have enough fish.",
"petdeath.wolf":"Your Wolf cub starved to death... He howled at the moon to the end.",
"petdeath.dragon":"Your Dragon starved to death... Even dragons need care.",
"petdeath.phoenix":"Your Phoenix starved to death... He didn't rise again. Not this time.",

// ===== ACHIEVEMENTS =====
"ach.title":"🏆 Achievements","ach.filter_all":"All","ach.filter_bronze":"🥉 Bronze",
"ach.filter_silver":"🥈 Silver","ach.filter_gold":"🥇 Gold",
"ach.unlocked":"Unlocked","ach.reward":"Reward",
"ach.new_ach":"🏆 New achievement","ach.plus_gems":"+{n} 💎",

// ===== QUESTS =====
"quests.title":"📜 Daily Quests","quests.reset":"⏰ Reset in",
"quests.claim":"🎁 Claim reward","quests.not_done":"Not completed yet",
"quests.claimed":"✅ Claimed",
"quest.taps_100.name":"Make 100 taps",
"quest.taps_500.name":"Make 500 taps",
"quest.taps_1000.name":"Make 1000 taps",
"quest.coins_10k.name":"Earn 10K coins",
"quest.coins_100k.name":"Earn 100K coins",
"quest.coins_1m.name":"Earn 1M coins",
"quest.buy_upgrades_5.name":"Buy 5 upgrades",
"quest.open_chest.name":"Open a chest",
"quest.catch_golden.name":"Catch a golden coin",
"quest.buy_skin.name":"Buy a skin",
"quest.deposit_up.name":"Upgrade deposit",
"quest.prestige_item.name":"Buy an item for shards",

// ===== LEADERS =====
"leaders.title":"🥇 Leaders","leaders.submit_hint":"Your nickname is locked to your profile. Submit your score?",
"leaders.submit":"📤 Submit score","leaders.loading":"Loading...",
"leaders.empty":"No records yet. Be the first! 🏆",
"leaders.not_connected":"Leaderboard not connected","leaders.sent":"✅ Score submitted!",

// ===== SKINS =====
"skins.title":"🎨 Skins","skins.btn_title":"🖲️ TAP button",
"skins.btn_hint":"Each skin — 5 💎","skins.emoji_title":"❤️ Emoji skins",
"skins.emoji_hint":"10 💎 each. Button turns into emoji",
"skins.bg_title":"🖼️ Game background","skins.bg_hint":"25 💎 each. Tap — on/off",
"skins.smile_title":"🎭 Deposit smiley","skins.smile_hint":"Only via promo code",
"skins.selected":"✓ Selected","skins.active":"✓ Active","skins.tap":"Tap",
"skins.promo_only":"Promo only",
"skins.name_gold":"Golden","skins.name_blue":"Blue","skins.name_green":"Green",
"skins.name_diamond":"Diamond","skins.name_ruby":"Ruby","skins.name_gennadii":"GENNADII",
"skins.name_heart":"Heart","skins.name_fire_heart":"Fire heart",
"skins.name_shield":"Shield","skins.name_candy":"Candy",
"skins.name_blood":"Blood mutation",

// ===== BACKGROUNDS =====
"bg.base":"Base","bg.space":"🌌 Space","bg.flame":"🔥 Flame","bg.ocean":"🌊 Ocean",
"bg.sakura":"🌸 Sakura","bg.ice":"❄️ Ice","bg.bloodmoon":"🌑 Blood Moon",
"bg.volcano":"🌋 Volcano","bg.nebula":"🌌 Nebula",

// ===== STATS =====
"stats.title":"📊 Statistics","stats.coins_now":"Current coins",
"stats.earned":"Total earned","stats.taps":"Taps made",
"stats.cps":"Coins per second","stats.per_click":"Per tap",
"stats.crystals":"Crystals","stats.shards":"Shards",
"stats.shards_total":"Total shards earned 🌑","stats.time":"Play time",
"stats.ach":"Achievements","stats.record":"🏆 Personal best",
"stats.minigame":"⏱️ Mini-game record","stats.taps_lower":"taps",

// ===== SETTINGS =====
"settings.title":"⚙️ Settings","settings.language":"🌐 Language",
"settings.float":"Show +N on tap","settings.golden":"Show golden coin",
"settings.daily":"Daily bonus","settings.sound":"Sound","settings.music":"Music",
"settings.low_particles":"Fewer particles","settings.krohlupic":"🐾 Show Krohlupic",
"settings.promo_title":"🎁 Promo code","settings.promo_ph":"Enter code...",
"settings.promo_btn":"Activate","settings.save_title":"💾 Progress saving",
"settings.export":"📤 Export progress",
"settings.export_hint":"Copy this code and keep it safe.",
"settings.copy":"📋 Copy","settings.import":"📥 Import progress",
"settings.import_hint":"Paste the code you saved earlier.",
"settings.import_ph":"Paste code here...","settings.import_load":"📥 Load",
"settings.advanced":"🔧 Advanced settings","settings.reset":"Reset all progress",
"settings.reset_confirm":"⚠️ All progress will be deleted!\nContinue?",

// ===== CONTACTS =====
"contacts.title":"📞 Contact the developer","contacts.tg":"Telegram channel",
"contacts.vk":"VK channel","contacts.support":"Contact developer",

// ===== ALMANAC =====
"almanac.title":"📖 Pets Almanac",
"almanac.subtitle":"Creatures that may join Krochlupic-Up","almanac.chance":"Drop chance",

// ===== FRIENDS =====
"friends.title":"👥 Friends","friends.my_id":"Your ID to share",
"friends.tab_list":"👥 Friends","friends.tab_requests":"✉️ Requests",
"friends.tab_search":"🔍 Find","friends.no_friends":"No friends yet. Find by ID →",
"friends.incoming":"📥 Incoming","friends.no_incoming":"No incoming requests",
"friends.outgoing":"📤 Outgoing","friends.no_outgoing":"No outgoing requests",
"friends.search_hint":"Enter friend's ID. Example: <b>Artem#A4K2</b>",
"friends.online":"🟢 <b>{online}</b> of <b>{total}</b> online",
"friends.status_online":"online","friends.status_away":"away","friends.status_offline":"offline",
"friends.was_online":"was online {time} ago","friends.copy_id":"Copy",
"friends.copied":"📋 Copied: {text}","friends.delete_confirm":"Remove from friends?",
"friends.gift_confirm":"Give 🎁 100 coins to {name}?",
"friends.gift_sent":"🎁 +100 coins sent!",
"friends.gift_already":"🎁 You already gave a gift today!",
"friends.gift_received":"🎁 Gifts: +{amount} coins from {senders}",
"friends.gift_no_coins":"Need at least 100 coins to gift!",

// ===== DM =====
"dm.title":"Message","dm.placeholder":"Write a message...",
"dm.hint":"Last 100 messages are kept","dm.loading":"Loading...",
"dm.empty":"Empty for now. Write first!","dm.loading_msgs":"Loading messages...",
"dm.send":"📤","dm.bad_word":"Message contains forbidden words",
"dm.too_fast":"Too fast! Wait {t} sec.",
"dm.not_friend":"This player is not in your friends","dm.chat":"💬 Chat",
"dm.clear":"🗑 Clear history","dm.clear_confirm":"Clear history? For all participants.",

// ===== COMPETITIONS =====
"comp.tab":"🏁 Competitions","comp.title":"Tap Battle",
"comp.subtitle":"Winner gets +1% of own balance.<br>Loser loses −1% of own balance.",
"comp.quick":"⚡ Quick match","comp.quick_hint":"Random opponent · 10 sec",
"comp.create_title":"👥 Create room","comp.create_btn":"🎮 Create room",
"comp.join_title":"🔑 Join room","comp.join_btn":"🚪 Join",
"comp.waiting":"⏳ Waiting for opponent...","comp.code_label":"Room code:",
"comp.copy_code":"📋 Copy code","comp.copied":"✅ Copied!",
"comp.cancel":"✖ Cancel","comp.cancel_confirm":"Cancel room?",
"comp.leave_confirm":"Leave competition?","comp.vs":"VS",
"comp.win":"🏆 VICTORY!","comp.lose":"💀 DEFEAT","comp.tie":"🤝 TIE",
"comp.your_taps":"Your taps","comp.opp_taps":"Opponent's taps",
"comp.reward_win":"💰 +{n} coins (1% balance)","comp.reward_lose":"💸 −{n} coins (1% balance)",
"comp.reward_tie":"Nobody gets anything","comp.exit":"✖ Exit","comp.close":"Close",
"comp.you":"Me","comp.opponent":"???",

// ===== AUCTION =====
"auction.tab":"🏪 Auction","auction.my_lots":"📦 My lots","auction.market":"🏪 Market",
"auction.create":"➕ List a pet","auction.create_title":"🏪 List on auction",
"auction.hint":"Pick a pet and set a price in coins",
"auction.commission":"Auction commission: 5%","auction.submit":"📤 List lot",
"auction.buy":"Buy","auction.cancel":"✖","auction.empty_my":"You have no active lots",
"auction.empty_market":"No lots. Check back later!","auction.err_price":"Enter price > 0",
"auction.err_storage_full":"Storage is full (5/5)",
"auction.err_no_coins":"Not enough coins",
"auction.confirm_buy":"Buy {pet} for {price} 💰?",
"auction.cancel_confirm":"Cancel lot and return pet?",

// ===== CLANS =====
"clan.tab_my":"🏰 My clan","clan.tab_search":"🔍 Search","clan.tab_create":"➕ Create",
"clan.no_clan_text":"You don't have a clan yet",
"clan.no_clan_hint":"Create your own for 500 💎 or find an existing one",
"clan.btn_create":"➕ Create clan","clan.btn_find":"🔍 Find clan",
"clan.stat_members":"Members","clan.stat_role":"Your role",
"clan.sub_members":"👥 Members","clan.sub_chat":"💬 Chat","clan.sub_requests":"✉️ Requests",
"clan.chat_ph":"Write a message...",
"clan.chat_hint":"Messages are visible to all clan members",
"clan.no_requests":"No requests","clan.btn_leave":"🚪 Leave clan",
"clan.btn_disband":"💀 Disband clan","clan.search_ph":"Name or tag",
"clan.search_hint":"Enter clan name or tag","clan.field_name":"Clan name",
"clan.field_name_ph":"3 to 20 characters","clan.field_tag":"Tag (2–4 symbols, A–Z)",
"clan.field_tag_ph":"KRL","clan.field_desc":"Description",
"clan.field_desc_ph":"Short description...","clan.field_type":"Join type",
"clan.type_open":"Open","clan.type_open_hint":"Join instantly",
"clan.type_closed":"Closed","clan.type_closed_hint":"By request",
"clan.create_cost":"Cost: 500 💎","clan.btn_create_submit":"🏗️ Create clan for 500 💎",
"clan.role_owner":"👑 Owner","clan.role_officer":"🛡 Officer","clan.role_member":"👤 Member",
"clan.btn_accept":"✓ Accept","clan.btn_decline":"✕","clan.btn_kick":"Kick",
"clan.btn_promote":"↑","clan.btn_demote":"↓",
"clan.kick_confirm":"Kick player from clan?",
"clan.err_name_short":"Name must be 3 to 20 characters",
"clan.err_tag_invalid":"Tag must be 2–4 latin letters",
"clan.err_tag_taken":"This tag is already taken",
"clan.err_not_enough_gems":"Not enough crystals (500 💎 needed)",
"clan.err_in_clan":"You are already in a clan",
"clan.err_chat_too_fast":"Not so fast! Wait a couple seconds",
"clan.err_name_bad":"Name contains forbidden words",
"clan.err_desc_bad":"Description contains forbidden words",
"clan.err_chat_bad":"Message contains forbidden words",
"clan.confirm_leave":"Leave the clan?",
"clan.confirm_disband":"Disband the clan? This action cannot be undone!",
"clan.joined":"✅ You joined the clan!","clan.request_sent":"✉️ Request sent",
"clan.left":"You left the clan","clan.disbanded":"Clan disbanded",
"clan.full":"Clan is full (10 / 10)","clan.btn_edit":"✏️ Edit clan",
"clan.edit_title":"✏️ Edit clan","clan.edit_save":"💾 Save changes",
"clan.invest_title":"💰 Invest in clan",
"clan.invest_hint":"Invested coins raise the clan level<br>and give <b>+1% income</b> to every member",
"clan.invest_custom":"How many coins to invest?\nYou have: {coins}",
"clan.invest_confirm":"Invest {amount} coins in clan?",
"clan.invest_done":"🏰 Invested {amount} in clan!",
"clan.invest_no_coins":"Not enough coins!\nNeed: {need}\nYou have: {have}",

// ===== PROFILE =====
"profile.title":"🏅 Profile","profile.hint":"Your nickname. It can't be changed.",
"profile.nick_ph":"Your nickname","profile.save":"✅ Save nickname",
"profile.err_short":"Nickname must be at least 2 characters",
"profile.err_long":"Nickname no longer than 15 characters",
"profile.err_chars":"Only letters, digits, space and _","profile.err_empty":"Nickname is empty",
"banner.title":"🎨 Profile banner",
"banner.hint":"Banners are earned from achievements, events and clan levels.",
"banner.new":"🎨 New banner: {name}!",
"banner.novice.name":"🥉 Novice","banner.novice.desc":"100 taps",
"banner.farmer.name":"🌾 Farmer","banner.farmer.desc":"Earn 1M coins",
"banner.veteran.name":"💠 Veteran","banner.veteran.desc":"1T earned",
"banner.master.name":"👑 Master","banner.master.desc":"50 achievements",
"banner.legend.name":"🌟 Legend","banner.legend.desc":"Top-1 leaderboard",
"banner.absolute.name":"🔱 Absolute","banner.absolute.desc":"Absolute lvl 699",
"banner.genesis.name":"💠 Genesis","banner.genesis.desc":"7 pets",
"banner.bloodlord.name":"🩸 Blood Lord","banner.bloodlord.desc":"10 comp. wins",

// ===== TUTORIAL =====
"tutorial.next":"Next ▶","tutorial.skip":"Skip ✕","tutorial.finish":"Finish ✓",
"tutorial.1":"👆 Tap the big button — you get coins",
"tutorial.2":"🛒 Buy upgrades in the Shop — income runs itself",
"tutorial.3":"⚡ Upgrade the generator to tap faster!",
"tutorial.4":"🎁 Open the Chest once per hour — crystals and shards inside",
"tutorial.5":"📜 Complete daily Quests — refreshed every day",
"tutorial.6":"🎨 Buy Skins and visit the Shop for 💎",
"tutorial.7":"🐾 On page 2 — Pets. Collect and feed them!",
"tutorial.8":"🕵️ There are many secret actions — try to find them!",

// ===== NOTES =====
"note.title":"📜 Notes","note.found":"Found notes","note.back":"← Back to list",
"note.empty":"No notes yet. They can be found in the game…","note.new":"📜 A note appeared...",
"note.note1.title":"Note #1",
"note.note1.text":"«He makes me press this damn button. I'm tired. Day and night I sit here and press it — for money. Only this will help…»",
"note.note2.title":"Note #2",
"note.note2.text":"«At first.. As I see it, everything looks beautiful, and.. It's so right, so many creatures united.. But one fact bothers me, why is all this, what's the point of such a business?»",
"note.note3.title":"Note #3",
"note.note3.text":"«Dear diary, I finally found a job!\nThis studio is the richest in this city, and.. I suspect in this world!»",
"note.note4.title":"Note #4",
"note.note4.text":"«I {NICK} agree with the terms and join the Krochlupic-Up company!»",
"note.note5.title":"Note #5",
"note.note5.text":"«Dear diary, I know this is silly, but... Actually, why should I share my feelings with a piece of paper?»",
"note.note6.title":"Note #6",
"note.note6.text":"«He's so cute, I've never seen races that were so adorable!»",
"note.note7.title":"Note #7",
"note.note7.text":"«I heard a scream, at the exit of the building, yesterday.. and today.. he's gone.. he was kidnapped! Definitely!»",
"note.sign.contract":"— Contract","note.sign.unknown":"— ???",

// ===== ADMIN =====
"admin.title":"👑 Admin Console",
"admin.hint":"Commands apply to <b>all players</b> on the server",
"admin.status_boost":"🟢 Online boost:","admin.status_event":"🎉 Active event:",
"admin.no":"none","admin.history":"📜 Command history","admin.no_history":"History is empty",
"admin.err_no_access":"❌ Access denied","admin.err_unknown_cmd":"❌ Unknown command. Type help",
"admin.ok":"✅ Done","admin.confirm_gift":"Send gift to all players?",
"admin.confirm_boost":"Enable global boost for everyone?",
"admin.confirm_event":"Start global event for everyone?",
"admin.gift_sent":"🎁 Gifts sent to all players",
"admin.boost_started":"⚡ Global boost activated","admin.boost_stopped":"⚡ Global boost turned off",
"admin.event_started":"🎉 Event started","admin.event_stopped":"🎉 Event stopped",
"admin.message_sent":"📢 Message sent",
"admin.promo_unlocked":"🔓 Admin feature unlocked. Go to Settings → Advanced.",
"admin.pass_prompt":"🔑 Enter password:","admin.pass_wrong":"❌ Wrong password",
"admin.hidden_btn":"🔐 Hidden settings",

// ===== FNF =====
"fnf.title":"🥊 BATTLE WITH KROHLUPIC","fnf.hp":"❤️ Lives","fnf.seconds_left":"sec",
"fnf.start":"▶️ Start battle",
"fnf.start_hint":"Arrows fall down — tap them on beat!",
"fnf.cooldown":"⏳ Next battle in","fnf.cooldown_ready":"Ready to battle!",
"fnf.win":"🏆 VICTORY!","fnf.lose":"💀 DEFEAT",
"fnf.win_text":"You survived to the end!\n\n🎵 Score: {score}\n❌ Misses: {miss}\n🔥 Max combo: {combo}×\n\nRewards:\n{rewards}",
"fnf.lose_text":"Krohlupic won...\n\n🎵 Score: {score}\n❌ Misses: {miss}\n🔥 Max combo: {combo}×",
"fnf.perfect":"🌟 PERFECT! Bonus ×2!",
"fnf.reward_gems":"💎 +{n} crystals","fnf.reward_shards":"🌑 +{n} shards",
"fnf.reward_coins":"🪙 +{n} coins","fnf.err_already":"Battle already in progress!",
"fnf.err_cooldown":"Too early! Next battle in {t}",

// ===== CHEST / WHEEL / DAILY / MINIGAME =====
"chest.collect":"✅ Collect",
"wheel.title":"🎡 Wheel of Fortune","wheel.spin_free":"🎁 Spin for free",
"wheel.spin_paid":"💰 Spin","wheel.free_used":"🎁 Tomorrow",
"wheel.free_used_alert":"Free spin already used!","wheel.paid_used":"💰 Tomorrow",
"wheel.paid_used_alert":"Paid spin already used!",
"wheel.no_coins":"Not enough coins!\nNeed: {need}",
"wheel.result_coins":"💰 Got {n} coins!","wheel.result_gems":"💎 +{n} crystals!",
"wheel.result_shards":"🌑 +{n} shards!","wheel.result_negcoins":"💀 Lost {n} coins!",
"wheel.result_neggems":"💀 −{n} crystals!","wheel.result_negshards":"💀 −{n} shards!",
"wheel.result_empty":"❌ Empty. Better luck next time!",
"wheel.timer_tomorrow":"Next spins — tomorrow at 9:00",
"wheel.timer_available":"1 free + 1 paid spin per day",
"wheel.timer_paid":"Paid spin available",
"wheel.spin_for":"Spin for","wheel.first_free":"Use free spin first",
"daily.title":"📅 Daily reward","daily.hint":"Spin the wheel once a day!",
"daily.spin":"🎁 Spin!","daily.already":"Already spun today! Come back tomorrow.",
"daily.done_today":"Claimed today",
"daily.timer":"Next reward — tomorrow at 9:00",
"daily.timer_tomorrow":"Next reward — tomorrow at 9:00",
"daily.timer_today":"1 free spin per day!",
"daily.result_coins":"💰 Got {n} coins!","daily.result_gems":"💎 +{n} crystals!",
"daily.result_shards":"🌑 +{n} shards!",
"daily.result_boost":"⚡ Booster ×{n} added to storage!",
"minigame.title":"⏱️ Mini-game: 10 seconds",
"minigame.hint":"Tap as fast as you can!","minigame.tap_btn":"👆 TAP!",
"minigame.taps":"Taps","minigame.best":"Best","minigame.start":"▶️ Start",
"minigame.restart":"🔁 Again","minigame.playing":"⏳ Playing...",
"minigame.ready":"Ready to play!","minigame.next":"Next game in",
"minigame.too_early":"Too early! Next game in {t}",
"minigame.result_new":"🎉 NEW RECORD! {taps} taps! +{reward} 💎",
"minigame.result":"Taps: {taps}. {reward}","minigame.result_reward":"Reward: +{n} 💎",
"minigame.result_try":"Try again!",

// ===== GENERATOR =====
"generator.title":"⚡ Button Generator","generator.level":"Level {n} / {max}",
"generator.level_word":"Level","generator.level_short":"Lvl",
"generator.speed":"Speed:","generator.speed_label":"Speed:",
"generator.drop_in":"Drop in:",
"generator.warning":"⚠️ Every 3 minutes the level drops by 1–5",
"generator.warning_line":"⚠️ Every 3 minutes the level drops by 1–5",
"generator.upgrade":"Upgrade:","generator.upgrade_btn":"⚡ Upgrade",
"generator.upgrade_btn_short":"Upgrade","generator.upgrade_price":"Upgrade:",
"generator.max":"✨ Maximum level!","generator.max_line":"✨ Maximum level!",
"generator.drop":"⚡ Generator dropped by {n} lvl. (now {level})",
"generator.no_coins":"Not enough coins!\nNeed: {need}\nYou have: {have}",
"generator.tap_per_sec":" tap/sec","generator.tap_per_sec_plural":" taps/sec",
"generator.tap_in_sec":"1 tap per ",

// ===== DEPOSIT =====
"deposit.title":"🏦 Deposit",
"deposit.buy_hint":"Buy the deposit for <b>1 Qa</b> coins to unlock the smiley.",
"deposit.buy_hint2":"The smiley will grow with each investment.",
"deposit.buy_line":"Buy the deposit for <b>1 Qa</b> coins to unlock the smiley.",
"deposit.grow_hint":"The smiley will grow with each investment.",
"deposit.buy_btn":"Buy deposit for 1 Qa",
"deposit.level":"Level {n} / 25","deposit.level_word":"Level",
"deposit.hungry":"😭 Hungry! Eats 5M coins per second",
"deposit.hungry_line":"😭 Hungry! Eats 5M coins per second",
"deposit.full":"✨ Full deposit! Smiley is fed and happy.",
"deposit.full_line":"✨ Full deposit! Smiley is fed and happy.",
"deposit.happy":"Smiley is happy","deposit.happy_line":"Smiley is happy",
"deposit.next":"Next level:","deposit.next_line":"Next level:",
"deposit.invest_btn":"💰 Invest","deposit.max_reached":"Maximum reached!",
"deposit.drop":"😭 Smiley dropped: {from} → {to}",

// ===== BOSS =====
"boss.title":"💀 BOSS SMILEY","boss.hint":"Tap the boss! Do it in 45 seconds.",
"boss.start":"🔥 Start fight","boss.again":"🔁 Again","boss.retry":"🔁 Try again",
"boss.win":"🏆 Victory! +25 🌑 blood shards!",
"boss.win_again":"🏆 Victory! (reward already claimed)",
"boss.lose":"💀 Failed! −{lost} coins.",

// ===== REWARD / ALARM =====
"reward.title":"🏅 Reward","reward.desc":"You upgraded Clicker to level 228!",
"reward.sub":"You deserve a special reward.","reward.claim":"🎁 Claim reward",
"reward.claimed":"🎉 You received +25 🌑 blood shards!",
"reward.tab_msg":"🏅 You upgraded Clicker to 228! Open the Reward tab!",
"alarm.text":"You haven't tapped in a while!<br>Tap the sign 5 times",

// ===== HELP =====
"help.title":"❓ How to play",
"help.1":"<b>1.</b> Tap the big button — you get coins.",
"help.2":"<b>2.</b> Buy upgrades in the shop.",
"help.3":"<b>3.</b> The golden coin gives x7 for 30 seconds.",
"help.4":"<b>4.</b> Achievements give 💎 (🥉=1, 🥈=3, 🥇=5).",
"help.5":"<b>5.</b> Chest once per hour — crystals, coins, shards, boosters.",
"help.6":"<b>6.</b> Offline income up to 8 hours.",
"help.7":"<b>7.</b> Button skins — 5 💎, emoji — 10 💎, backgrounds — 25 💎.",
"help.8":"<b>8.</b> Items for 🌑 — 3 levels.",
"help.9":"<b>9.</b> Deposit — smiley drops a level every 30 minutes.",
"help.10":"<b>10.</b> Generator — increases tap speed.",
"help.11":"<b>11.</b> Leaderboard — rating by «Total earned».",
"help.12":"<b>12.</b> Quests refresh at 6:00.",
"help.13":"<b>13.</b> 🐾 Pets — buy eggs, feed them, get bonuses.",
"help.14":"<b>14.</b> The active pet must be well-fed or it will die!",
"help.15":"<b>15.</b> 🌪️ Blood Storm — every Monday at 9:00!",
"help.16":"<b>16.</b> 👥 Friends — share your ID, add friends, watch online status!",
"help.17":"<b>17.</b> 🏰 Clans — create your own for 500 💎 or join an existing one!",
"help.18":"<b>18.</b> 🥊 FNF battle — tap arrows on the beat!",

// ===== EVENTS =====
"event.rain":"💰 Coin rain","event.storm":"⚡ Lightning potential",
"event.fast":"🏃 Fast way","event.income":"💵 Income",
"event.super_storm":"🌪️ BLOOD STORM!",
"event.blood_moon":"🌕 BLOOD MOON 🌕\nIncome x2!",
"event.theft_start":"🚨 «THEFT» event started! About 22% of coins will be lost.",
"event.theft_end":"🚨 Theft ended. Total stolen: {n} coins",

// ===== SECRET =====
"secret.title":"⚡ Clicker 67","secret.subtitle":"Secret auto-clicker",
"secret.desc":"Makes 67 clicks per second automatically.",
"secret.unlock_hint_1":"You need to make","secret.taps_word":"taps",
"secret.your_taps":"Your taps","secret.unlock_btn":"🔒 Unlock",
"secret.unlocked_ok":"✅ Auto-clicker unlocked!",
"secret.activate":"🔥 Activate (67 Qa)",
"secret.activate_again":"🔥 Activate again (67 Qa)",
"secret.status_default":"Unlocked. Activation: 67 Qa for 30 minutes.",
"secret.active":"🔥 Auto-clicker active — 67 clicks/sec. Time left: {time}",
"secret.too_early":"❌ Too early!\nNeed {need} taps.\nLeft: {left}",
"secret.no_coins":"❌ Need 67 Qa!","secret.unlocked":"🔥 Clicker 67 unlocked!",
"secret.stopped":"⏸️ Clicker 67 stopped.",

// ===== PROMO =====
"promo.enter_code":"Enter code.","promo.used":"This code has already been used.",
"promo.invalid":"Invalid code.",

// ===== BOOSTERS =====
"booster.boost2":"Boost ×2","booster.boost2.desc":"Multiplier ×2 for 15 minutes",
"booster.boost3":"Boost ×3","booster.boost3.desc":"Multiplier ×3 for 10 minutes",
"booster.boost5":"Boost ×5","booster.boost5.desc":"Multiplier ×5 for 5 minutes",
"booster.activate_btn":"Activate","booster.none":"Out of stock",
"booster.other_active":"Another active","booster.already":"Already active",
"booster.in_stock":"In stock","booster.active_label":"Active",
"booster.left_label":"left",

// ===== CRYSTAL SHOP =====
"crystal.coinsBag":"Coin bag","crystal.coinsBag.desc":"1 hour of coin income",
"crystal.boost2":"Boost ×2","crystal.boost2.desc":"Multiplier ×2 for 15 min → to storage",
"crystal.boost3":"Boost ×3","crystal.boost3.desc":"Multiplier ×3 for 10 min → to storage",
"crystal.boost5":"Boost ×5","crystal.boost5.desc":"Multiplier ×5 for 5 min → to storage",
"crystal.chest":"Instant chest","crystal.chest.desc":"Opens chest immediately",
"crystal.depositUp":"+1 deposit level","crystal.depositUp.desc":"Only if deposit is bought",
"crystal.in_storage":"In storage:","crystal.will_give":"Will give",
"crystal.cps_zero":"CPS is 0 so far","crystal.buy_deposit_first":"Buy deposit first",
"crystal.deposit_max":"Deposit at maximum","crystal.level_short":"Lvl",
"crystal.will_open":"Opens immediately",

// ===== ITEMS / UPGRADES =====
"item.not_bought":"Not bought · Lvl 0/3","item.max":"Maximum · Lvl 3/3",
"item.level_short":"Lvl","item.upgrade_short":"Upgrade",
"up.max":"✓ Maximum","up.max_short":"Maximum","up.buy_short":"Buy",
"up.buy":"Buy ×{mult}","up.bought":"Bought:","up.level_label":"Level:",
"up.unlock10":"🔒 {price}💎","up.unlock25":"🔒 {price}💎",
"up.unlock10_confirm":"Unlock ×10 for {price} 💎?",
"up.unlock25_confirm":"Unlock ×25 for {price} 💎?",

// ===== GLOBAL UPGRADES =====
"globalup.superClicker":"🌟 Super Clicker",
"globalup.superClicker.desc":"+1 to base tap per level",
"globalup.bloodLuck":"🩸 Blood Luck",
"globalup.bloodLuck.desc":"+1% blood shard chance during Blood Moon",
"globalup.absoluteBoost":"🔱 Will of Absolute",
"globalup.absoluteBoost.desc":"+5% income from Absolute",
"globalup.genesisBoost":"💠 Echo of Genesis",
"globalup.genesisBoost.desc":"+3% income from Genesis",
"globalup.inactive":"Currently: inactive",
"globalup.now_click":"Currently: +","globalup.now_chance":"Currently: +",
"globalup.now_income":"Currently: +",

// ===== UPGRADES =====
"up.clicker":"👆 Clicker","up.clicker.desc":"+1 coin per tap",
"up.farm":"🌾 Farm","up.farm.desc":"+1 coin per second",
"up.factory":"🏭 Factory","up.factory.desc":"+10 coins per second",
"up.bank":"🏦 Bank","up.bank.desc":"+100 coins per second",
"up.server":"🖥️ Server room","up.server.desc":"+1000 coins per second",
"up.lab":"🔬 Laboratory","up.lab.desc":"+10000 coins per second",
"up.space":"🚀 Space station","up.space.desc":"+100K coins per second",
"up.quantum":"⚛️ Quantum computer","up.quantum.desc":"+1M coins per second",
"up.portal":"🌀 Portal","up.portal.desc":"+10M coins per second",
"up.galaxy":"🌌 Galaxy","up.galaxy.desc":"+100M coins per second",
"up.universe":"🌠 Universe","up.universe.desc":"+1B coins per second",
"up.multiverse":"♾️ Multiverse","up.multiverse.desc":"+10B coins per second",
"up.singularity":"🕳️ Singularity","up.singularity.desc":"+100B coins per second",
"up.godmode":"👁️ Eye of Creator","up.godmode.desc":"+1T coins per second",
"up.infinity":"💫 Infinity","up.infinity.desc":"+10T coins per second",
"up.timecrystal":"🕰️ Time crystal","up.timecrystal.desc":"+100T coins per second",
"up.blackhole":"🌑 Black hole","up.blackhole.desc":"+1Qa coins per second",
"up.omega":"♎ Omega","up.omega.desc":"+10Qa coins per second",
"up.eternity":"🌌 Eternity","up.eternity.desc":"+100Qa coins per second",
"up.creation":"✨ Creator","up.creation.desc":"+2Qi coins per second",
"up.absolute":"🔱 Absolute","up.absolute.desc":"+20Qi coins per second",
"up.transcend":"🕉️ Transcendence","up.transcend.desc":"+60Qi coins per second",
"up.genesis":"💠 Genesis","up.genesis.desc":"+500Qi coins per second",

// ===== ITEMS =====
"item.blade":"Blood blade","item.blade.desc":"Weapon of the first hunters",
"item.amulet":"Moon amulet","item.amulet.desc":"Talisman of black stone",
"item.elixir":"Blood elixir","item.elixir.desc":"Potion of moon dew",
"item.candle":"Ritual candle","item.candle.desc":"Burns with eternal scarlet light",
"item.skull":"Enemy skull","item.skull.desc":"Trophy from the battlefield",
"item.bat":"Bat","item.bat.desc":"Keeper of the night",
"item.orb":"Dark orb","item.orb.desc":"Sees through time",
"item.scythe":"Moon scythe","item.scythe.desc":"Reaps enemies like wheat",
"item.wings":"Vampire wings","item.wings.desc":"Gift of night hunting",
"item.crown":"Moon crown","item.crown.desc":"Power over the Blood Moon",
"item.throne":"Throne of the Blood Lord","item.throne.desc":"Legendary throne of the scarlet era",

// ===== FORTUNES =====
"fortune.label":"The cookie says:","fortune.close":"Thanks, cookie!",
"fortune.1":"Luck is on your side today. Tap boldly!",
"fortune.2":"One tap — and the world will change. Maybe this one?",
"fortune.3":"The smiley is pleased with you today. Don't let it down.",
"fortune.4":"A good day to buy upgrades.",
"fortune.5":"If something doesn't work out — just tap more.",
"fortune.6":"The Blood Moon knows more about you than you think.",
"fortune.7":"It's watching. It always watches.",
"fortune.8":"Crystals come to the patient.",
"fortune.9":"Today you will find what you've been looking for.",
"fortune.10":"Not all clickers are equally useful. Some are destiny.",
"fortune.11":"Notes are not just text. It's a warning.",
"fortune.12":"You tap too much. But not sure.",
"fortune.13":"Pahan approves your choice.",
"fortune.14":"Sometimes the best move is to stop. But not today.",
"fortune.15":"Today is a good day for a record.",
"fortune.16":"Your smiley dreams of level 25.",
"fortune.17":"Blood shards love the persistent.",
"fortune.18":"If you see a golden coin — don't miss it.",
"fortune.19":"One click separates you from greatness.",
"fortune.20":"Today you can do anything. Even buy a skin.",
"fortune.21":"The mystery is closer than it seems. Just dig deeper.",
"fortune.22":"Don't forget about the chest. It's waiting.",
"fortune.23":"Something good will happen in 67 taps.",
"fortune.24":"Today a star named You is rising.",
"fortune.25":"The world is a clicker. You are its player.",
"fortune.26":"Listen to music. It knows the rhythm of luck.",
"fortune.27":"Not all secrets need to be sought. Some will find you.",
"fortune.28":"Today no one will catch up with you in the leaderboard.",
"fortune.29":"A day when what you wished on tap 228 comes true.",
"fortune.30":"Smile at the smiley — and it will smile back.",
"fortune.31":"Whoever reads this is already a winner.",
"fortune.32":"Two clicks — and you're closer to the goal.",
"fortune.33":"Life is like a chest: open it — and you'll find out.",
"fortune.34":"Crystals are frozen time. Take care of them.",
"fortune.35":"Today is better than yesterday. And that's a fact.",
"fortune.36":"Someone is watching your success. Keep going.",
"fortune.37":"A good prediction always comes true. This is one.",
"fortune.38":"Not all that glitters is gold. But the coin is definitely yours.",

// ===== SOCIAL =====
"social.online":"🟢 <b>{online}</b> of <b>{total}</b> online",
"social.was_online":"was online {time} ago","social.copy_success":"📋 Copied: {text}",
"social.gift_sent":"🎁 +100 coins sent!",
"social.gift_received":"🎁 Gifts: +{amount} coins from {senders}",

// ===== SUBSCRIBE =====
"subscribe.title":"Subscribe to our channels!",
"subscribe.sub":"Lots of useful stuff: news, updates, events",
"subscribe.ok":"✅ Got it",

// ===== KROHLUPIC QUOTES =====
"khrquote.coins_100":"Look, we have 100 already! The start of something big.",
"khrquote.coins_1k":"1,000 coins! I'm so proud. Really. I mean it.",
"khrquote.coins_100k":"100K? Hey, you grow fast!",
"khrquote.coins_1m":"A million! Looks like you'll actually make it.",
"khrquote.coins_1b":"A billion. You know, we even got chairs in the office!",
"khrquote.coins_1t":"A trillion… Awkward to ask, but is that a lot?",
"khrquote.coins_1qa":"Quadrillion! Do you ever sleep?",
"khrquote.coins_1qi":"Quintillion. I'm even afraid to say it.",
"khrquote.coins_1sp":"I thought we'd never get there. But you did it.",
"khrquote.coins_1no":"But... How... This is a number that shouldn't be on the balance. Oh.",
"khrquote.taps_10":"One, two, three... Oops, I can't keep up!",
"khrquote.taps_100":"You try so hard. I appreciate it.",
"khrquote.taps_1k":"Doesn't your finger hurt? Mine would.",
"khrquote.taps_10k":"10,000! Are you a machine?",
"khrquote.taps_100k":"My paws are tired from watching.",
"khrquote.taps_1m":"A million taps. I don't even know what to say.",
"khrquote.up_farm":"A farm! Now coins come on their own. Convenient!",
"khrquote.up_factory":"The factory is working. We're expanding, you know?",
"khrquote.up_bank":"A bank! Soon we'll be taking loans.",
"khrquote.up_space":"Space! I heard there are other clickers out there.",
"khrquote.up_galaxy":"Wow. You're not building a business, you're building a universe.",
"khrquote.up_genesis":"Genesis… This is the beginning. Or the end? I'm not sure.",
"khrquote.ach_first":"An achievement! You're doing great. Really.",
"khrquote.ach_50":"Half the achievements! You're persistent.",
"khrquote.ach_all":"You... collected everything. I'm proud. And a little scared.",
"khrquote.ev_theft_start":"Theft! Hide your coins! Hurry!",
"khrquote.ev_theft_end":"Phew. We made it. I think.",
"khrquote.ev_bloodmoon":"Look, the moon is red! Income ×2, but be careful.",
"khrquote.note_found":"Another note? Who writes them?..",
"khrquote.cute_1":"I was thinking... you're a good person.",
"khrquote.cute_2":"Sometimes I just like watching you tap.",
"khrquote.cute_3":"You have great taste in upgrades, you know?",
"khrquote.cute_4":"I like being on the same team as you.",
"khrquote.cute_5":"A rabbit-programmer isn't much, but I try.",
"khrquote.strange_1":"Listen... do you remember where I came from? I don't. Strange.",
"khrquote.strange_2":"Sometimes I think someone is watching you. But it's probably nothing.",
"khrquote.strange_3":"I heard a sound yesterday. Like... someone tapping not here.",
"khrquote.strange_4":"The one from the notes. He was here before. I almost remember him.",
"khrquote.strange_5":"If I ever disappear — don't look for me. Just keep tapping.",
"khrquote.strange_6":"This button never ends, does it? Never. Do you understand?",
"khrquote.strange_7":"Don't go into room 9. Oh. Forget I said anything.",
"khrquote.back_1":"You're back! I was starting to think I'd been left here alone.",
"khrquote.back_2":"Oh! Hi. I was sitting here looking at the button. She's pretty.",
"khrquote.back_3":"You were gone a while. I missed you. And the coins missed you.",

// ===== ALERT MESSAGES =====
"alert.not_enough_coins":"❌ Not enough coins!\nNeed: {0}\nYou have: {1}",
"alert.not_enough_crystals":"❌ Not enough crystals!\nNeed: {0}\nYou have: {1}",
"alert.not_enough_shards":"❌ Not enough shards!\nNeed: {0}\nYou have: {1}",
"alert.not_enough_xp":"❌ Not enough XP!",
"alert.promo_only":"🎁 Promo code only!",
"alert.booster_active":"⚡ Booster already active, wait for it to end!",
"alert.booster_none":"📦 No boosters in storage!",
"alert.offline_coins":"💰 Got {0} coins!",
"alert.export_empty":"❌ No save to export.",
"alert.export_error":"❌ Export error: {0}",
"alert.export_copied":"✅ Copied!",
"alert.export_copy_fail":"❌ Failed to copy. Select text and copy manually.",
"alert.import_empty":"❌ Paste save code.",
"alert.import_bad_format":"❌ Invalid save format.",
"alert.import_confirm":"⚠️ Current progress will be replaced.\nContinue?",
"alert.import_loaded":"✅ Progress loaded! Reloading...",
"alert.import_error":"❌ Import error: {0}",
"alert.daily_bonus":"📅 Daily bonus! Streak day {0}.\n+{1} coins!",
"alert.daily_bonus_week":"🎁 +5 💎 for 7-day streak!",
"alert.leaderboard_no_firebase":"❌ Leaderboard not connected.",
"alert.leaderboard_no_nick":"❌ Set a nickname first!",
"alert.set_nickname":"❌ Set a nickname first!",
"alert.pet_storage_full":"❌ Storage is full (5/5)!",
"alert.pet_nest_busy":"❌ Nest is busy! Wait for it to finish.",
"alert.deposit_buy_first":"❌ Buy the deposit first!",
"alert.deposit_max":"❌ Deposit already at max (lvl 25)!",
"alert.competition_room_taken":"❌ Room already taken!",
"alert.competition_not_found":"❌ Room not found!",
"alert.competition_wrong_code":"❌ Code must be 4 characters!",
"alert.fnf_already":"❌ Battle already in progress!",
"alert.fnf_cooldown":"⏳ Too early! Next battle in {0}"
}
};

// ===== HELPER FUNCTIONS =====
var currentLang="ru";

function loadLangPref(){
try{var saved=localStorage.getItem(LANG_KEY);if(saved&&LANG[saved]){currentLang=saved;return true;}}catch(e){}
return false;
}
function saveLangPref(){try{localStorage.setItem(LANG_KEY,currentLang);}catch(e){}}

// t() — с подстановкой {0}, {1}, ... и конвертацией \n
function t(key){
var v=LANG[currentLang]&&LANG[currentLang][key];
if(v===undefined)v=LANG.ru&&LANG.ru[key];
if(v===undefined)return key;
if(arguments.length>1){
for(var i=1;i<arguments.length;i++){
v=v.split("{"+(i-1)+"}").join(arguments[i]);
}
}
v=v.replace(/\\n/g,"\n");
return v;
}
function tt(key){
var s=t(key);
if(arguments.length>1){
for(var i=1;i<arguments.length;i++){
s=s.split("{"+(i-1)+"}").join(arguments[i]);
}
}
return s;
}
function ttMap(key,map){
var s=t(key);
if(map){
for(var k in map){
s=s.split("{"+k+"}").join(map[k]);
}
}
return s;
}
function setLang(code,skipSave){
if(!LANG[code])return;
currentLang=code;
if(!skipSave)saveLangPref();
applyLang();
document.documentElement.lang=code;
}
function applyLang(){
document.querySelectorAll("[data-i18n]").forEach(function(el){
el.innerHTML=t(el.dataset.i18n);
});
document.querySelectorAll("[data-i18n-ph]").forEach(function(el){
el.setAttribute("placeholder",t(el.dataset.i18nPh));
});
document.querySelectorAll(".lang-btn").forEach(function(b){
if(b.dataset.lang===currentLang)b.classList.add("active");
else b.classList.remove("active");
});
try{window.dispatchEvent(new CustomEvent("langchange",{detail:{lang:currentLang}}));}catch(e){}
}
function detectBrowserLang(){
var nav=(navigator.language||navigator.userLanguage||"ru").toLowerCase();
if(nav.indexOf("ru")===0)return "ru";
if(nav.indexOf("en")===0)return "en";
return "ru";
}
function hasLangPref(){try{return !!localStorage.getItem(LANG_KEY);}catch(e){return false;}}
function getLang(){return currentLang;} 
